modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="${issue_url}" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
logoFile="logo.png" #optional
displayTest = "IGNORE_ALL_VERSION"
credits = """
Thanks to:
  Authors:
    juliand665
    LostLuma

  Contributors:
    altrisi
    DenaryDev
    dima-dencep
    EuropaYou
    N4TH4NOT
    parly
    Pixaurora
    Setadokalo
    Siphalor
    sisby-folk
    triphora

  Translators:
    AlphaKR93
    Altegar
    BurrConnie
    DecafDawren
    egeesin
    EuropaYou
    Felix14-v2
    FITFC
    GuNanOvO
    Hubry
    ImVietnam
    ishi-sama
    kyrtion
    LotuxPunk
    Madis0
    mpustovoi
    notlin4
    Pixaurora
    raspberrygitq
    Rhbarber
    RinixGG
    Samekichi
    Taarek
    TheBossMagnus
    TheLegendofSaram
    wicivo
    XfedeX
"""
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="${forge_version_range}" #mandatory
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"